FROM python:3.9
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bullseye stable" > /etc/apt/sources.list.d/docker.list && \
    apt-get update && apt-get install -y --no-install-recommends librdkafka-dev openjdk-11-jre-headless docker-ce-cli && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/local/lib/docker/cli-plugins && \
    curl --fail -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/lib/docker/cli-plugins/docker-compose && \
    chmod +x /usr/local/lib/docker/cli-plugins/docker-compose && \
    cp /usr/local/lib/docker/cli-plugins/docker-compose /usr/local/bin/docker-compose

COPY requirements.txt /requirements.txt
RUN pip3 install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r /requirements.txt
